ingress: https://www.ansatt.dev.nav.no/tiltakspenger/meldekort
env:
  - name: MELDEKORT_API_URL
    value: http://tiltakspenger-meldekort-api
  - name: MELDEKORT_API_SCOPE
    value: dev-gcp:tpts:tiltakspenger-meldekort-api
replicas:
  min: 1
  max: 2