apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tpts
  name: tiltakspenger-meldekort
  namespace: tpts

spec:
  ingresses:
    - {{ ingress }}
  image: {{ image }}
  port: 3050
  env:
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: tiltakspenger-meldekort-api
  replicas:
    max: 1
    min: 1
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: idporten-loa-high
  tokenx:
    enabled: true
