apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: tiltakspenger-meldekort
  namespace: tpts

spec:
  image: { { image } }
  port: 3000
  env:
    - name: NEXT_PUBLIC_TELEMETRY_URL
      value: { { NEXT_PUBLIC_TELEMETRY_URL } }
    - name: UNLEASH_SERVER_API_URL
      value: { { unleash.url } }
    - name: DEKORATOR_ENV
      value: { { dekorator.env } }
  ingresses:
    - { { ingress } }
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
