apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tpts
  name: tiltakspenger-meldekort
  namespace: tpts

spec:
  ingresses:
    - {{ ingress }}
  image: {{ image }}
  port: 3050
  env:
  {{#each env}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: tiltakspenger-meldekort-api
  replicas:
  {{#with replicas}}
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  {{/with}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /tiltakspenger/meldekort/demo/**
      level: idporten-loa-substantial
  tokenx:
    enabled: true
