apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tpts
  name: tiltakspenger-meldekort
  namespace: tpts

spec:
  ingresses:
    - https://tiltakspenger-meldekort.ansatt.dev.nav.no
  image: { { image } }
  port: 3000
  env:
    - name: NEXT_PUBLIC_TELEMETRY_URL
      value: { { NEXT_PUBLIC_TELEMETRY_URL } }
    - name: UNLEASH_SERVER_API_URL
      value: { { unleash.url } }
    - name: DEKORATOR_ENV
      value: { { dekorator.env } }
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
