name: Build for deploy

on:
  workflow_call:
    outputs:
      IMAGE:
        description: "Docker image"
        value: ${{ jobs.build.outputs.IMAGE }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      READER_TOKEN:
        required: true
      SLACK_VARSEL_WEBHOOK_URL:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      IMAGE: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build app
        run: npm run build
        env:
          ASSETS_URL: https://cdn.nav.no/tpts/tp-meldekort
      - name: Upload static assets to Nav CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: tpts
          source: ./server/dist/client/assets
          destination: tp-meldekort
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: tpts
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
