name: Build, push, and deploy to dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/.build-and-test.yml
    permissions:
      contents: read
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}

  build:
    name: Build and push
    uses: ./.github/workflows/.build-for-deploy.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  deploy-dev:
    name: Deploy to NAIS (dev)
    needs: [test, build]
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}
