name: Test/build on feature branch push

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Test and build
    uses: ./.github/workflows/.build-and-test.yml
    permissions:
      contents: read
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
